services:
  - type: web
    name: office-ticket-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: SESSION_SECRET
        generateValue: true
      - key: HELPER_LOGIN
        value: helper
      - key: HELPER_PASSWORD
        sync: false
      - key: STAFF_LOGIN
        value: staff
      - key: STAFF_PASSWORD
        sync: false
      - key: ACTIVATION_PASSWORD_ADOPTFOUND
        sync: false
      - key: ACTIVATION_PASSWORD_CULTLDA
        sync: false
      - key: ACTIVATION_PASSWORD_ALASTORGRUM
        sync: false
      - key: ACTIVATION_PASSWORD_CONTROLLER2001
        sync: false
      - key: ACTIVATION_PASSWORD_MEMERTENS
        sync: false
      - key: ACTIVATION_PASSWORD_VALDR_QUICK
        sync: false
      - key: ACTIVATION_PASSWORD_MARKEVI4
        sync: false
      - key: ACTIVATION_PASSWORD_SANGRERRR
        sync: false
      - key: ACTIVATION_PASSWORD_SHIZUKAXIII
        sync: false
      - key: ACTIVATION_PASSWORD_MISHOK22
        sync: false
      - key: ACTIVATION_PASSWORD_IWANTTOFLYXXX
        sync: false
      - key: TZ
        value: Europe/Moscow
